config/routes.rb
Rails.application.routes.draw do

  root "salaries#index"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :salaries
  resources :salary_checks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/salary.rb
class Salary < ApplicationRecord
  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :salaries
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
  
end

app/controllers/salaries_controller.rb
class SalariesController < ApplicationController
  def index
    @salaries = Salary.all
  end
  
  def show
    @salary = Salary.find(params[:id]) 
    @salary_amount = @salary.salary_amount
    @result1 = (1030000 - @salary_amount)
    @result2 = (1030000 - @salary_amount)/12
  end
  
  def new
   @salary = Salary.new
   
  end
  
  def create
    @salary = Salary.new(salary_params)
    
    if @salary.save
      redirect_to salary_path(@salary)
      
    end
  end
  
  def update
    @salary = Salary.find(params[:id])
    if @salary.update(salary_params)
      redirect_to @salary, notice: 'Salary was successfully updated.'
    else
      render :edit
    end
  end
  
  def destroy
    @salary = Salary.find(params[:id])
    @salary.destroy
    redirect_to salaries_path, notice: 'Salary was successfully destroyed.'
  end
  
  private
    def salary_params
      params.require(:salary).permit(:date, :salary_amount, :transportation_expenses).merge(user_id: current_user.id)
    end
  
end

app/controllers/salary_checks_controller.rb
class SalaryChecksController < ApplicationController
  def index
    @salaries = Salary.all
  end

  def show
    @salary = Salary.find(params[:id])
  end

  def edit
    @salary = Salary.find(params[:id])
  end
  
  def update
    @salary = Salary.find(params[:id])
    if @salary.update(salary_params)
      redirect_to @salary, notice: 'Salary was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @salary = Salary.find(params[:id])
    @salary.destroy
    redirect_to salary_checks_path, notice: 'Salary was successfully destroyed.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/helpers/salary_checks_helper.rb
module SalaryChecksHelper
end

app/views/layouts/_footer.html.erb
<footer class="text-black text-center mt-5">
  <p class="py-2" style="font-size: 12px;">
    @2024 Salary Automatic calculation.All rights reserved.
  </p>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar bg-white shadow-sm">
  <div class="container-fluid">
    <%= link_to root_path, data: { turbolinks: false }, class: "navbar-brand" do %>
      <%= image_tag "logo.png", class: "img-fluid", width: "200px" %>
    <% end %>
    <div class="d-flex justify-content-between align-items-center">
    
      <% if user_signed_in? %>
      
      <div class="header-text d-flex align-items-center">
        税金一覧表
        勤務先の設定
        <%= link_to "給料チェック", salary_checks_path, class: "btn text-purple me-3", data: { turbolinks: false } %>
        ユーザー名
      </div>
      
        <div class="dropdown">
          <a class="dropdown-toggle text-purple" data-bs-toggle="dropdown" href="#"></a>
            <div class="dropdown-menu dropdown-menu-end shadow text-center" style="padding: 4px 0px;">
              <%= link_to "アカウント編集", edit_user_registration_path, class: "dropdown-item text-secondary border-bottom py-2", data: { turbolinks: false } %>
              <%= link_to "ログアウト", destroy_user_session_path, class: "dropdown-item text-secondary py-2", method: :delete %>
            </div>
        </div>
        
    
      <% else %>
        <div class="d-flex align-items-center">
          <%= link_to "ログイン", new_user_session_path, class: "btn text-purple me-3", data: { turbolinks: false } %>
          <%= link_to "無料会員登録", new_user_registration_path, class: "btn btn-purple me-5 px-3 py-2", data: { turbolinks: false } %>
        </div>
       
      <% end %>
        
      
    </div>
  </div>
</nav>    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>給料自動計算ツール</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    
    <%= yield %>
    
    <%= render "layouts/footer" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/salaries/index.html.erb
<div class="top-content row text-center pt-4">
  <div class="fw-bold">
    <p>学生さん向け！気にするべき税金対策が一目でわかる</p>
  </div>
  <div class="top-content-title">
    <h4>扶養内103万円以内で、今年</h4>
    <h4>あとどれくらい稼げるのか計算できます</h4>
  </div>
  <div class="pt-3">
    <p>今月の給与額を基準にして、毎月あとどれくらいのペースで稼げば<br>
    扶養内の103万円に収まるか自動で計算することができます。</p>
  </div>
  
  <% if user_signed_in? %>
  <div class="salary-input-btn">
    <%= link_to '給料入力画面へ', new_salary_path %>
  </div>
  <% end %>
</div>

app/views/salaries/new.html.erb
<div class="container w-100">
  <div class="text-center my-4">
    <h2>給料入力画面</h2>
  </div>
    <div class="row justify-content-center">
      <div class="col-10 col-md-6">
      <%= form_with model: @salary, url: salaries_path, local: true, class: 'salary-form'  do |f| %>
        
        <div class="mb-4">
          <%= f.label :date, '給料日', class: "text-secondary fw-bold mb-2" %>
          <%= f.date_field :date, autofocus: true, autocomplete: 'date', class: "form-control shadow-sm py-md-3" %>
        </div>
        
        <div class="mb-4" style="position: relative;">
          <%= f.label :salary_amount, '給与額', class: "text-secondary fw-bold mb-2" %>
          <%= f.number_field :salary_amount, autofocus: true, autocomplete: 'salary_amount', placeholder: "0", class: "form-control shadow-sm py-md-3" %>
          <span class="money-input" style="position: absolute;">円</span>
        </div>
        
        <div class="mb-4" style="position: relative;">
          <%= f.label :transportation_expenses, '交通費', class: "text-secondary fw-bold mb-2" %>
          <%= f.number_field :transportation_expenses, autofocus: true, autocomplete: 'transportation_expenses', placeholder: "0", class: "form-control shadow-sm py-md-3" %>
          <span class="money-input" style="position: absolute;">円</span>
        </div>
        
        <!--<最後にそれぞれのボタンレイアウト修正>-->
        <div class="d-flex justify-content-between">
          <div class="my-5 text-center">
            <%= f.submit "計算する", class: "fw-bold py-3 w-100" %>
          </div>
          
          <div class="my-5 text-center">
            <%= f.button "リセットする", type: :reset, class: "fw-bold py-3 w-100" %>
          </div>
        </div>
          
        
      </div>
    <% end %>
  </div>
</div>

app/views/salaries/show.html.erb
<div class="text-center my-4">
  <h2>計算結果</h2>
  <p class="calculation_result1">103万円まで残り<span class="result1"><%= @result1 %>円</span>です</p><br>
  <p class="average_result2">毎月平均<span class="result2"><%= @result2 %>円</span>稼ぐことができます</p>
  <%= link_to "給料チェック画面へ", salary_checks_path, class: "btn text-purple", data: { turbolinks: false } %>
</div>

app/views/salary_checks/destroy.html.erb
<h1>SalaryChecks#destroy</h1>
<p>Find me in app/views/salary_checks/destroy.html.erb</p>

app/views/salary_checks/edit.html.erb
<div class="container">
  <div class="text-center my-4">
    <h2>給料情報編集画面</h2>
  </div>
  
    <div class="row justify-content-center">
      
      <div class="col-10 col-md-6">
       <%= form_with model: @salary, url: salary_path, local: true, class: 'salary-form'  do |f| %>
        <%#= render "devise/shared/error_messages" %>
        
        <div class="mb-4">
          <%= f.label :date, '給料日', class: "text-secondary fw-bold mb-2" %>
          <%= f.date_field :date, autofocus: true, autocomplete: 'date', class: "form-control shadow-sm py-md-3" %>
        </div>
        
        <div class="mb-4" style="position: relative;">
          <%= f.label :salary_amount, '給与額', class: "text-secondary fw-bold mb-2" %>
          <%= f.number_field :salary_amount, autofocus: true, autocomplete: 'salary_amount', placeholder: "0", class: "form-control shadow-sm py-md-3" %>
          <span class="money-input" style="position: absolute;">円</span>
        </div>
        
        <div class="mb-4" style="position: relative;">
          <%= f.label :transportation_expenses, '交通費', class: "text-secondary fw-bold mb-2" %>
          <%= f.number_field :transportation_expenses, autofocus: true, autocomplete: 'transportation_expenses', placeholder: "0", class: "form-control shadow-sm py-md-3" %>
          <span class="money-input" style="position: absolute;">円</span>
        </div>
      
        <div class="my-5 text-center">
          <%= f.submit "更新する", class: "fw-bold py-3 w-50" %>
        </div>
       <% end %>
      </div>
      
      </div>  
    </div>
  
  <%= link_to "給料チェック画面に戻る", salary_checks_path, class: "btn text-purple me-3", data: { turbolinks: false } %>
</div>

app/views/salary_checks/index.html.erb
<div class="container">
  <div class="text-center my-4">
    <h2>給料チェック</h2>
  </div>
  
 <table>
  <thead>
    <tr>
      <th>給料日</th>
      <th>給与額</th>
      <th>交通費</th>
      
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>
  <tbody>
    <% @salaries.each do |salary| %>
      <tr>
        <td><%= salary.date %></td>
        <td><%= salary.salary_amount %>円</td>
        <td><%= salary.transportation_expenses %>円</td>
        
        <td><%= link_to "編集", edit_salary_check_path(salary.id) %></td>
        
        <td><%= button_to "削除", salary_check_path(salary.id), { method: :delete, form: { data: { confirm: "本当に削除しますか？" } } } %></td>

      </tr>
    <% end %>
  </tbody>
 </table>
  
  
  
</div>

app/views/salary_checks/show.html.erb
<div class="container">
  <div class="text-center my-4">
    <h2>給料詳細画面</h2>
  </div>
  
   <table>
    <thead>
      <tr>
        <th>給料日</th>
        <th>給与額</th>
        <th>交通費</th>
        <!-- 他のカラムを追加 -->
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @salary.date %></td>
        <td><%= @salary.salary_amount %>円</td>
        <td><%= @salary.transportation_expenses %>円</td>
      </tr>
    </tbody>
 　</table>
  
  <%= link_to "給料チェック画面に戻る", salary_checks_path, class: "btn text-purple me-3", data: { turbolinks: false } %>
</div>